name = "PlateReaderCurves"
uuid = "6f2f3989-c7f3-41ed-b3c9-102d028c40aa"
authors = ["Thomas Poulsen"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
CSV = "0.8"
Plots = "1.9"
julia = "1.5.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
